import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, FileText, Ban, RotateCcw, AlertTriangle, ShieldCheck, CreditCard, XCircle, User, Settings, Calendar, Banknote } from 'lucide-react';
import { mockBookings } from '../../data/mockBookings';

export default function BookingEdit() {
  const navigate = useNavigate();
  const { id } = useParams();
  
  const booking = mockBookings.find(b => b.invoice === id) || mockBookings[0];
  const refTitle = booking.moduleType === 'flights' ? 'PNR Number' : booking.moduleType === 'visa' ? 'Application ID' : 'Booking Reference';

  return (
    <div className="space-y-6 max-w-5xl animate-in fade-in duration-300">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-gray-200 pb-4">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate(-1)} className="p-2 bg-gray-700 text-white rounded-lg hover:bg-gray-800 transition-colors shadow-sm">
            <ArrowLeft size={20} />
          </button>
          <div>
            <h2 className="text-2xl font-bold text-gray-800">Edit Booking</h2>
            <div className="flex items-center gap-2 text-sm text-gray-500 mt-1 capitalize">
              Invoice: <span className="font-bold text-gray-700">{booking.invoice}</span> • {booking.moduleType} / {booking.moduleName.split('\n')[0]}
            </div>
          </div>
        </div>
        <div className="flex gap-2">
          <button className="flex items-center gap-2 bg-gray-800 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-900 transition-colors shadow-sm">
            <CreditCard size={16} /> Mark Paid
          </button>
          <button className="flex items-center gap-2 bg-emerald-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-emerald-700 transition-colors shadow-sm">
            <CheckCircle2 size={16} /> Confirm Booking
          </button>
        </div>
      </div>

      {/* Actions */}
      <div className="bg-white rounded-xl shadow-soft border border-gray-100 p-6">
        <div className="flex justify-between items-center mb-6 pb-2 border-b border-gray-100">
          <h3 className="text-sm font-bold text-gray-800 flex items-center gap-2"><Settings size={16} /> Actions</h3>
          <span className="text-xs text-gray-500">Quick Actions</span>
        </div>

        <div className="flex flex-col md:flex-row gap-6 mb-6">
          <div className="flex-1 bg-blue-50/50 border border-blue-100 rounded-xl p-5 flex gap-4">
            <ShieldCheck className="text-blue-500 flex-shrink-0" size={24} />
            <div>
              <h4 className="font-bold text-blue-900 mb-1">Important: Action Guidelines</h4>
              <p className="text-xs text-blue-800 mb-3">These actions are processed by third-party suppliers and cannot be undone once triggered</p>
              <div className="grid grid-cols-2 gap-y-2 text-xs text-blue-800">
                <p className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-blue-600"/> <span className="font-bold">Issue / Confirm:</span> Secures reservation with provider</p>
                <p className="flex items-center gap-1.5"><Ban size={14} className="text-red-500"/> <span className="font-bold">Void:</span> Cancel before issuance</p>
                <p className="flex items-center gap-1.5"><XCircle size={14} className="text-red-500"/> <span className="font-bold">Cancel:</span> Cancel after issuance</p>
                <p className="flex items-center gap-1.5"><RotateCcw size={14} className="text-orange-500"/> <span className="font-bold">Refund Request:</span> Refund transaction</p>
              </div>
            </div>
          </div>
          
          <div className="w-full md:w-64 bg-emerald-50/30 border border-emerald-100 rounded-xl p-5">
            <h4 className="font-bold text-emerald-800 flex items-center gap-2 mb-3"><FileText size={16}/> {refTitle}</h4>
            <div className="bg-white border border-gray-200 rounded p-2 text-gray-700 font-mono font-bold text-sm mb-3">{booking.ref}</div>
            <p className="text-[11px] text-gray-500 flex items-center gap-1 mb-1"><AlertTriangle size={12}/> Generated by supplier</p>
            <p className="text-[11px] text-gray-500 flex items-center gap-1"><Calendar size={12}/> Created: {booking.createdAt}</p>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <button className="flex items-center justify-center gap-2 bg-emerald-600 text-white py-3 rounded-lg text-sm font-bold hover:bg-emerald-700 transition-colors shadow-sm">
            <CheckCircle2 size={18} /> Issue Booking
          </button>
          <button className="flex items-center justify-center gap-2 bg-gray-200 text-gray-600 py-3 rounded-lg text-sm font-bold hover:bg-gray-300 transition-colors">
            <Ban size={18} /> Void Booking
          </button>
          <button className="flex items-center justify-center gap-2 bg-gray-200 text-gray-600 py-3 rounded-lg text-sm font-bold hover:bg-gray-300 transition-colors">
            <XCircle size={18} /> Cancel Booking
          </button>
          <button className="flex items-center justify-center gap-2 bg-gray-200 text-gray-600 py-3 rounded-lg text-sm font-bold hover:bg-gray-300 transition-colors">
            <RotateCcw size={18} /> Refund Request
          </button>
        </div>
      </div>

      {/* Financial Details */}
      <div className="bg-white rounded-xl shadow-soft border border-gray-100 p-6">
        <div className="flex justify-between items-center mb-6 pb-2 border-b border-gray-100">
          <h3 className="text-sm font-bold text-gray-800 flex items-center gap-2"><Banknote size={16} /> Financial Details</h3>
          <span className="text-xs text-gray-500">Pricing & Commission</span>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-6">
          <div><label className="block text-xs font-medium text-gray-700 mb-1">Booking Status <span className="text-red-500">*</span></label><select className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm outline-none"><option>{booking.booking.split('\n')[0]}</option><option>CONFIRMED</option><option>CANCELLED</option></select></div>
          <div><label className="block text-xs font-medium text-gray-700 mb-1">Payment Status <span className="text-red-500">*</span></label><select className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm outline-none"><option>{booking.payment}</option><option>PAID</option></select></div>
          <div><label className="block text-xs font-medium text-gray-700 mb-1">Original Price <span className="text-red-500">*</span></label><input type="text" defaultValue={`USD ${(Number(booking.price) - Number(booking.earning)).toFixed(2)}`} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm outline-none" /></div>
          <div><label className="block text-xs font-medium text-gray-700 mb-1">Final Price</label><input type="text" defaultValue={`USD ${booking.price}`} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm outline-none" /></div>
          <div><label className="block text-xs font-medium text-gray-700 mb-1">Commission</label><input type="text" defaultValue={`USD ${booking.earning}`} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm outline-none font-bold text-emerald-600" /></div>
        </div>
      </div>

      {/* Guest Information */}
      <div className="bg-white rounded-xl shadow-soft border border-gray-100 p-6">
        <div className="flex justify-between items-center mb-6 pb-2 border-b border-gray-100">
          <h3 className="text-sm font-bold text-gray-800 flex items-center gap-2"><User size={16} /> Primary Customer</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="grid grid-cols-2 gap-4">
            <div><label className="block text-xs font-medium text-gray-700 mb-1">Name <span className="text-red-500">*</span></label><input type="text" defaultValue={booking.user.split('\n')[0]} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm outline-none" /></div>
            <div><label className="block text-xs font-medium text-gray-700 mb-1">Email <span className="text-red-500">*</span></label><input type="email" defaultValue={booking.user.split('\n')[1]} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm outline-none" /></div>
          </div>
        </div>
      </div>

    </div>
  );
}